---
#title: "Character Sheet"
format:
  html:
    css: styles.css
---

<div class="resume-image-container">
  <div class="resume-content">
  <h1>Character Sheet</h1>
  <div class="resume-column">
  <section class="resume-section-skills">
    <h2>Skills</h2>
    <ul>
      <li>Data analysis and visualization</li>
      <li>Experiment and survey design</li>
      <li>Interviewing</li>
      <li>Recruiting and scheduling</li>
      <li>Social psychology</li>
    </ul>
  </section>

  <section class="resume-section-skills">
    <h2>Software & Languages</h2>
    <ul>
      <li>R/RStudio</li>
      <li>Excel</li>
      <li>Shiny & Quarto</li>
      <li>Qualtrics</li>
      <li>Youcanbook.me</li>
    </ul>
  </section>
  </div>
  
  <section class="resume-section-education">
    <h2>Education</h2>
    <h3>University of Massachusetts Boston, Boston, MA</h3>
    <ul>
      <li>Graduate Certificate in Survey Research: Dec 2023 & Expected, Ph D: Sociology, May 2025</li>
    </ul>
    <h3>University of North Carolina at Charlotte, Charlotte, NC</h3>
    <ul>
      <li>Master of Arts: Sociology, May 2020 & Bachelor of Arts: Sociology, May 2017</li>
    </ul>
  </section>
  
  <section class="resume-section-jobs">
    <h2>Experience</h2>
    <h3>Clinial Research Coordinator</h3>
    <ul>
      <li>Programmed R scripts using tidyverse to clean and transform complex data from REDCap for analysis. Produce descriptive statistics of twelve clinical sites for reports to stakeholders and principal investigators. Presented the reports at weekly leadership meetings.</li>
      <li>Conducted in-depth psychiatric assessments of patients with schizophrenia using clinician rated instruments and software including PANSS, QLS, NIH Toolbox and WebCNP to rate cognitive, social, and community functioning.</li>
      <li>Helped design and maintain the Project SUCCESS open scholar website that was showcased by BIDMC's Chief Academic Officer. Set up and maintained the project's subscription audience in MailChimp.</li>
    </ul>
    <h3>Research Assistant</h3>
    <ul>
      <li>Conceptualized, developed, and tested a tool/application to measure subjective time. Designed in Figma, simulated in Netlogo, and developed in a Shiny R application connected to a MySQL database server.</li>
      <li>Analyzed SurveyUSA and Elon University polling data to visualize descriptive statistics in preparation for a regional conference. Additionally, I computed a predictive multinomial regression model in R.</li>
      <li>Collaborated with a team to qualitatively code and analyze six-hundred news articles under a major time constraint.</li>
      <li>Conducted semi-structured in-depth interviews to parse out cognition, culture, and structure of time in the workplace. Produced wordclouds in R to visualize qualitative information.</li>
    </ul>
    <h3>Lab Manager and Research Assistant</h3>
    <ul>
      <li>Collected quantitative, acoustic, and interview data from three hundred experimental sessions.</li>
      <li>Trained a team of graduate and undergraduate students to conduct experimental sessions.</li>
      <li>Scheduled a team of research assistants and three hundred participants for three coinciding experiments.</li>
    </ul>
  </section>
  
  </div>
</div>

